region: us-east-1

function_name: sfr-oclc-lookup-development
handler: service.handler
description: Service that returns data from a single MARCXML object identified by an OCLC#
runtime: python3.6
role: lambda_basic_execution

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id:
aws_secret_access_key:

# dist_directory: dist
timeout: 60
memory_size: 128


# If `tags` is uncommented then tags will be set at creation or update
# time.  During an update all other tags will be removed except the tags
# listed here.
tags:
  sfr: sfr

# Build options
build:
  source_directories: lib, helpers # a comma delimited list of directories in your project root that contains source to package.

# Environment Variables
# Any variables set here will be carried across all environemnts. To set
# specific variables (for dev/qa/prod) modify the individual .yaml files
# in the config directory
# NOTE: The surrounding === comments enable the replacing and must be kept in
# the file
# === START_ENV_VARIABLES ===
environment_variables:
  ENV: development
  LOG_LEVEL: info
# === END_ENV_VARIABLES ===
